behaviors:
  Car:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 8192
      learning_rate: 0.00003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.925
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 64
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
      gail:
        strength: 1.0
        gamma: 0.99
        encoding_size: 128
        demo_path: demos/Car.demo
    keep_checkpoints: 10
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 10000
    threaded: true
    